### ISSUE TITLE
PyPI updates

### ISSUE THREAD

**Issue by CompoTypo** [gremwell/pynessus#12]
My team uses Poetry to manage dependencies for a variety of reasons

The project looks like its exactly what we need but the PyPi for it hasn't been updated in a bit and the wheel build is failing
```
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-mcdn5pmj/python-nessus_b2a10e6af8d3490f96a6e989812f5243/setup.py", line 2, in <module>
      VERSION = __import__("pynessus").__version__
    File "/tmp/pip-install-mcdn5pmj/python-nessus_b2a10e6af8d3490f96a6e989812f5243/pynessus/__init__.py", line 2, in <module>
      from nessus import Nessus, NessusAPIError
  ModuleNotFoundError: No module named 'nessus'
```

@QKaiser would you mind updating that package, please? :)

**Comment by qkaiser** [comment]
I'll take a look at it next week and keep you posted.
